server:
  port: 8761
eureka:
  server:
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 1000
  instance:
    appname: 3MP-AGW-REGISTRY
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
